In [1]:
# Importing required libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pickle
from os import path
import os

# Importing necessary classes for data preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# Importing functions for evaluating model performance
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Importing functions for data splitting and training models
from sklearn.model_selection import train_test_split

# Importing various machine learning algorithms
from sklearn.svm import SVC  # Support Vector Classifier
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

In [2]:
# Displaying concise information about the dataset
dns = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\dns.csv")
ldap = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ldap.csv")
mssql = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\mssql.csv")
netbios = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\netBIOS.csv")
ntp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ntp.csv")
snmp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\snmp.csv")
ssdp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ssdp.csv")
syn = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\syn.csv")
tftp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\tftp.csv")
udp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\udp.csv")
udplag = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\udplag.csv")

C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:2: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  dns = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\dns.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:3: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  ldap = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ldap.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:4: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  mssql = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\mssql.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:5: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  netbios = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\netBIOS.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:6: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  ntp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ntp.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:7: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  snmp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\snmp.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  ssdp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\ssdp.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  tftp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\tftp.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:11: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  udp = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\udp.csv")
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1795816709.py:12: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  udplag = pd.read_csv("C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\udplag.csv")

In [3]:
# Displaying concise information about the dataset
datasets = ["dns", "ldap", "mssql", "netbios", "ntp", "snmp", "ssdp", "syn", "tftp", "udp", "udplag"]

data = {}

for dataset_name in datasets:
    file_path = f"C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\{dataset_name}.csv"
    data[dataset_name] = pd.read_csv(file_path)
    print(f"{dataset_name}.shape:", data[dataset_name].shape)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

dns.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

ldap.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

mssql.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

netbios.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

ntp.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

snmp.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

ssdp.shape: (40000, 89)
syn.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

tftp.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

udp.shape: (40000, 89)
udplag.shape: (40000, 89)

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3422072084.py:8: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

In [4]:
import pandas as pd
from IPython.display import display

datasets = ["dns", "ldap", "mssql", "netbios", "ntp", "snmp", "ssdp", "syn", "tftp", "udp", "udplag"]

data = {}

for dataset_name in datasets:
    file_path = f"C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\{dataset_name}.csv"
    data[dataset_name] = pd.read_csv(file_path)
    print(f"{dataset_name}.head(n=5):")
    display(data[dataset_name].head())

dns.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,425,172.16.0.5-192.168.50.1-634-60495-17,172.16.0.5,634,192.168.50.1,60495,17,51:39.8,28415,...,0.0,0,0,0.0,0.0,0,0,0,1,DrDoS_DNS
1,1,430,172.16.0.5-192.168.50.1-60495-634-17,192.168.50.1,634,172.16.0.5,60495,17,51:39.8,2,...,0.0,0,0,0.0,0.0,0,0,0,0,DrDoS_DNS
2,2,1654,172.16.0.5-192.168.50.1-634-46391-17,172.16.0.5,634,192.168.50.1,46391,17,51:39.9,48549,...,0.0,0,0,0.0,0.0,0,0,0,1,DrDoS_DNS
3,3,2927,172.16.0.5-192.168.50.1-634-11894-17,172.16.0.5,634,192.168.50.1,11894,17,51:39.9,48337,...,0.0,0,0,0.0,0.0,0,0,0,1,DrDoS_DNS
4,4,694,172.16.0.5-192.168.50.1-634-27878-17,172.16.0.5,634,192.168.50.1,27878,17,51:39.9,32026,...,0.0,0,0,0.0,0.0,0,0,0,1,DrDoS_DNS

ldap.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,21010,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:22:40.254769,9141643,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
1,1,20932,172.16.0.5-192.168.50.1-900-1808-17,172.16.0.5,900,192.168.50.1,1808,17,2018-12-01 11:22:40.255361,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
2,2,27876,172.16.0.5-192.168.50.1-900-58766-17,172.16.0.5,900,192.168.50.1,58766,17,2018-12-01 11:22:40.255568,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
3,3,24270,172.16.0.5-192.168.50.1-900-35228-17,172.16.0.5,900,192.168.50.1,35228,17,2018-12-01 11:22:40.256113,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP
4,4,5109,172.16.0.5-192.168.50.1-900-44969-17,172.16.0.5,900,192.168.50.1,44969,17,2018-12-01 11:22:40.256285,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_LDAP

mssql.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,139,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 11:32:32.915441,119151083,...,2.853681e+07,67834732.0,4024278.0,5975510.0,98.183502,5975622.0,5975358.0,0,1,DrDoS_MSSQL
1,1,38385,172.16.0.5-192.168.50.1-850-20345-17,172.16.0.5,850,192.168.50.1,20345,17,2018-12-01 11:32:32.915442,1,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
2,2,27033,172.16.0.5-192.168.50.1-851-21631-17,172.16.0.5,851,192.168.50.1,21631,17,2018-12-01 11:32:32.915578,1,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
3,3,34348,172.16.0.5-192.168.50.1-852-15332-17,172.16.0.5,852,192.168.50.1,15332,17,2018-12-01 11:32:32.915773,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL
4,4,19225,172.16.0.5-192.168.50.1-853-41853-17,172.16.0.5,853,192.168.50.1,41853,17,2018-12-01 11:32:32.916114,2,...,0.000000e+00,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_MSSQL

netbios.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,256565,172.16.0.5-192.168.50.1-34012-2334-17,172.16.0.5,34012,192.168.50.1,2334,17,2018-12-01 11:47:08.463789,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
1,1,252918,172.16.0.5-192.168.50.1-34013-50170-17,172.16.0.5,34013,192.168.50.1,50170,17,2018-12-01 11:47:08.464316,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
2,2,174257,172.16.0.5-192.168.50.1-34014-61534-17,172.16.0.5,34014,192.168.50.1,61534,17,2018-12-01 11:47:08.464472,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
3,3,185193,172.16.0.5-192.168.50.1-34015-8930-17,172.16.0.5,34015,192.168.50.1,8930,17,2018-12-01 11:47:08.464520,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS
4,4,198671,172.16.0.5-192.168.50.1-34016-33040-17,172.16.0.5,34016,192.168.50.1,33040,17,2018-12-01 11:47:08.464925,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_NetBIOS

ntp.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,0,172.16.0.5-192.168.50.1-60675-80-6,172.16.0.5,60675,192.168.50.1,80,6,2018-12-01 09:17:11.183810,5220876,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,205.174.165.72/c.php,1,DrDoS_NTP
1,1,7,172.16.0.5-192.168.50.1-60676-80-6,172.16.0.5,60676,192.168.50.1,80,6,2018-12-01 09:17:11.205636,12644252,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,DrDoS_NTP
2,2,12858,192.168.50.7-65.55.163.78-50458-443-6,65.55.163.78,443,192.168.50.7,50458,6,2018-12-01 09:17:12.634569,3,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
3,3,10191,192.168.50.7-65.55.163.78-50465-443-6,65.55.163.78,443,192.168.50.7,50465,6,2018-12-01 09:17:13.458370,3,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0,1,BENIGN
4,4,239,192.168.50.253-224.0.0.5-0-0-0,192.168.50.253,0,224.0.0.5,0,0,2018-12-01 09:17:13.470913,114329232,...,2.466441,15.0,6.0,9527428.0,248706.681286,9950741.0,9092248.0,0,0,BENIGN

snmp.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,109857,172.16.0.5-192.168.50.1-528-47330-17,172.16.0.5,528,192.168.50.1,47330,17,2018-12-01 12:00:13.902782,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP
1,1,238192,172.16.0.5-192.168.50.1-529-26888-17,172.16.0.5,529,192.168.50.1,26888,17,2018-12-01 12:00:13.902785,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP
2,2,82963,172.16.0.5-192.168.50.1-530-3723-17,172.16.0.5,530,192.168.50.1,3723,17,2018-12-01 12:00:13.903230,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP
3,3,205787,172.16.0.5-192.168.50.1-531-38862-17,172.16.0.5,531,192.168.50.1,38862,17,2018-12-01 12:00:13.903311,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP
4,4,83411,172.16.0.5-192.168.50.1-532-35383-17,172.16.0.5,532,192.168.50.1,35383,17,2018-12-01 12:00:13.903490,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SNMP

ssdp.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,72,172.16.0.5-192.168.50.1-0-0-0,172.16.0.5,0,192.168.50.1,0,0,2018-12-01 12:23:13.663425,119714230,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
1,1,55171,172.16.0.5-192.168.50.1-700-36081-17,172.16.0.5,700,192.168.50.1,36081,17,2018-12-01 12:23:13.663475,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
2,2,39545,172.16.0.5-192.168.50.1-701-25269-17,172.16.0.5,701,192.168.50.1,25269,17,2018-12-01 12:23:13.663526,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
3,3,20334,172.16.0.5-192.168.50.1-702-2533-17,172.16.0.5,702,192.168.50.1,2533,17,2018-12-01 12:23:13.663622,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP
4,4,18397,172.16.0.5-192.168.50.1-703-34942-17,172.16.0.5,703,192.168.50.1,34942,17,2018-12-01 12:23:13.663844,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_SSDP

syn.head(n=5):

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,281052,172.16.0.5-192.168.50.1-53058-53058-6,172.16.0.5,53058,192.168.50.1,53058,6,2018-12-01 13:30:30.741451,115799309,...,646237.483665,1709809.0,1.0,1.426117e+07,3.220326e+06,21714933.0,11043464.0,0,1,Syn
1,1,450424,172.16.0.5-192.168.50.1-32237-32237-6,172.16.0.5,32237,192.168.50.1,32237,6,2018-12-01 13:30:30.741452,113973933,...,19.595918,49.0,1.0,1.628198e+07,2.573891e+06,20019405.0,11993631.0,0,1,Syn
2,2,182979,172.16.0.5-192.168.50.1-60495-9840-6,172.16.0.5,60495,192.168.50.1,9840,6,2018-12-01 13:30:30.741501,112,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn
3,3,41540,172.16.0.5-192.168.50.1-59724-59724-6,172.16.0.5,59724,192.168.50.1,59724,6,2018-12-01 13:30:30.741563,105985004,...,17.705259,48.0,1.0,1.514071e+07,3.077366e+06,20954123.0,11120336.0,0,1,Syn
4,4,358711,172.16.0.5-192.168.50.1-60496-32538-6,172.16.0.5,60496,192.168.50.1,32538,6,2018-12-01 13:30:30.741565,1,...,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0,1,Syn

tftp.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,46970,172.16.0.5-192.168.50.1-64670-64670-6,172.16.0.5,64670,192.168.50.1,64670,6,2018-12-01 13:34:27.403713,13120080,...,0.0,1.0,1.0,13120078.0,0.0,13120078.0,13120078.0,0,1,TFTP
1,1,164775,172.16.0.5-192.168.50.1-16405-16405-6,172.16.0.5,16405,192.168.50.1,16405,6,2018-12-01 13:34:27.404124,3990342,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP
2,2,177893,172.16.0.5-192.168.50.1-45838-45838-6,172.16.0.5,45838,192.168.50.1,45838,6,2018-12-01 13:34:27.404125,11842236,...,0.0,1.0,1.0,11842234.0,0.0,11842234.0,11842234.0,0,1,TFTP
3,3,82756,172.16.0.5-192.168.50.1-27049-27049-6,172.16.0.5,27049,192.168.50.1,27049,6,2018-12-01 13:34:27.404177,3579644,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP
4,4,153782,172.16.0.5-192.168.50.1-43305-27049-6,172.16.0.5,43305,192.168.50.1,27049,6,2018-12-01 13:34:27.404228,90,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,TFTP

udp.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,101418,172.16.0.5-192.168.50.1-43443-6652-17,172.16.0.5,43443,192.168.50.1,6652,17,2018-12-01 12:36:57.628026,218395,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
1,1,21564,172.16.0.5-192.168.50.1-54741-9712-17,172.16.0.5,54741,192.168.50.1,9712,17,2018-12-01 12:36:57.628076,108219,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
2,2,23389,172.16.0.5-192.168.50.1-56589-4680-17,172.16.0.5,56589,192.168.50.1,4680,17,2018-12-01 12:36:57.628164,104579,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
3,3,48872,172.16.0.5-192.168.50.1-40233-2644-17,172.16.0.5,40233,192.168.50.1,2644,17,2018-12-01 12:36:57.628166,110967,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP
4,4,80354,172.16.0.5-192.168.50.1-33989-16901-17,172.16.0.5,33989,192.168.50.1,16901,17,2018-12-01 12:36:57.628217,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_UDP

udplag.head(n=5):

C:\Users\user\AppData\Local\Temp\ipykernel_4116\3653216687.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

,Unnamed: 0.1,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,0,186059,172.16.0.5-192.168.50.1-58445-4463-17,172.16.0.5,58445,192.168.50.1,4463,17,2018-12-01 13:04:45.928673,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
1,1,135692,172.16.0.5-192.168.50.1-36908-9914-17,172.16.0.5,36908,192.168.50.1,9914,17,2018-12-01 13:04:45.928913,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
2,2,33822,172.16.0.5-192.168.50.1-41727-32361-17,172.16.0.5,41727,192.168.50.1,32361,17,2018-12-01 13:04:45.928915,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
3,3,24498,172.16.0.5-192.168.50.1-55447-5691-17,172.16.0.5,55447,192.168.50.1,5691,17,2018-12-01 13:04:45.929024,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag
4,4,117372,172.16.0.5-192.168.50.1-58794-56335-17,172.16.0.5,58794,192.168.50.1,56335,17,2018-12-01 13:04:45.929096,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,UDP-lag

In [5]:
# List of dataset names
datasets = ["dns", "ldap", "mssql", "netbios", "ntp", "snmp", "ssdp", "syn", "tftp", "udp", "udplag"]

# Dictionary to store loaded datasets
data = {}

# Load datasets and store them in the data dictionary
for dataset_name in datasets:
    file_path = f"C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\{dataset_name}.csv"
    data[dataset_name] = pd.read_csv(file_path)

# Iterate through each dataset and check for missing values
for dataset_name, dataset in data.items():
    print(f"Missing Values - {dataset_name}")
    cnt = 0
    for col in dataset.columns:
        missing_mask = dataset[col].isnull() | (dataset[col] == '-')  # Check for NaN or '-'
        missing_count = missing_mask.sum()
        if missing_count > 0:
            cnt += 1
            print(f"\t{col}: {missing_count} missing values")
    print(f"Total {cnt} features with missing values\n")

C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)
C:\Users\user\AppData\Local\Temp\ipykernel_4116\1555916417.py:10: DtypeWarning: Columns (86) have mixed types. Specify dtype option on import or set low_memory=False.
  data[dataset_name] = pd.read_csv(file_path)

Missing Values - dns
	Flow Bytes/s: 2 missing values
Total 1 features with missing values

Missing Values - ldap
Total 0 features with missing values

Missing Values - mssql
	Flow Bytes/s: 2 missing values
Total 1 features with missing values

Missing Values - netbios
Total 0 features with missing values

Missing Values - ntp
	Flow Bytes/s: 8 missing values
Total 1 features with missing values

Missing Values - snmp
Total 0 features with missing values

Missing Values - ssdp
Total 0 features with missing values

Missing Values - syn
	Flow Bytes/s: 3467 missing values
Total 1 features with missing values

Missing Values - tftp
	Flow Bytes/s: 4041 missing values
Total 1 features with missing values

Missing Values - udp
Total 0 features with missing values

Missing Values - udplag
Total 0 features with missing values

In [6]:
dns.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')

In [7]:
dns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 89 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0.1                  40000 non-null  int64
 1   Unnamed: 0                    40000 non-null  int64
 2   Flow ID                       40000 non-null  object
 3    Source IP                    40000 non-null  object
 4    Source Port                  40000 non-null  int64
 5    Destination IP               40000 non-null  object
 6    Destination Port             40000 non-null  int64
 7    Protocol                     40000 non-null  int64
 8    Timestamp                    40000 non-null  object
 9    Flow Duration                40000 non-null  int64
 10   Total Fwd Packets            40000 non-null  int64
 11   Total Backward Packets       40000 non-null  int64
 12  Total Length of Fwd Packets   40000 non-null  int64
 13   Total Length of Bwd Packets  40000 non-null  int64
 14   Fwd Packet Length Max        40000 non-null  int64
 15   Fwd Packet Length Min        40000 non-null  int64
 16   Fwd Packet Length Mean       40000 non-null  float64
 17   Fwd Packet Length Std        40000 non-null  float64
 18  Bwd Packet Length Max         40000 non-null  int64
 19   Bwd Packet Length Min        40000 non-null  int64
 20   Bwd Packet Length Mean       40000 non-null  float64
 21   Bwd Packet Length Std        40000 non-null  float64
 22  Flow Bytes/s                  39998 non-null  float64
 23   Flow Packets/s               40000 non-null  float64
 24   Flow IAT Mean                40000 non-null  float64
 25   Flow IAT Std                 40000 non-null  float64
 26   Flow IAT Max                 40000 non-null  int64
 27   Flow IAT Min                 40000 non-null  int64
 28  Fwd IAT Total                 40000 non-null  int64
 29   Fwd IAT Mean                 40000 non-null  float64
 30   Fwd IAT Std                  40000 non-null  float64
 31   Fwd IAT Max                  40000 non-null  int64
 32   Fwd IAT Min                  40000 non-null  int64
 33  Bwd IAT Total                 40000 non-null  int64
 34   Bwd IAT Mean                 40000 non-null  float64
 35   Bwd IAT Std                  40000 non-null  float64
 36   Bwd IAT Max                  40000 non-null  int64
 37   Bwd IAT Min                  40000 non-null  int64
 38  Fwd PSH Flags                 40000 non-null  int64
 39   Bwd PSH Flags                40000 non-null  int64
 40   Fwd URG Flags                40000 non-null  int64
 41   Bwd URG Flags                40000 non-null  int64
 42   Fwd Header Length            40000 non-null  float64
 43   Bwd Header Length            40000 non-null  int64
 44  Fwd Packets/s                 40000 non-null  float64
 45   Bwd Packets/s                40000 non-null  float64
 46   Min Packet Length            40000 non-null  int64
 47   Max Packet Length            40000 non-null  int64
 48   Packet Length Mean           40000 non-null  float64
 49   Packet Length Std            40000 non-null  float64
 50   Packet Length Variance       40000 non-null  float64
 51  FIN Flag Count                40000 non-null  int64
 52   SYN Flag Count               40000 non-null  int64
 53   RST Flag Count               40000 non-null  int64
 54   PSH Flag Count               40000 non-null  int64
 55   ACK Flag Count               40000 non-null  int64
 56   URG Flag Count               40000 non-null  int64
 57   CWE Flag Count               40000 non-null  int64
 58   ECE Flag Count               40000 non-null  int64
 59   Down/Up Ratio                40000 non-null  int64
 60   Average Packet Size          40000 non-null  float64
 61   Avg Fwd Segment Size         40000 non-null  float64
 62   Avg Bwd Segment Size         40000 non-null  float64
 63   Fwd Header Length.1          40000 non-null  float64
 64  Fwd Avg Bytes/Bulk            40000 non-null  int64
 65   Fwd Avg Packets/Bulk         40000 non-null  int64
 66   Fwd Avg Bulk Rate            40000 non-null  int64
 67   Bwd Avg Bytes/Bulk           40000 non-null  int64
 68   Bwd Avg Packets/Bulk         40000 non-null  int64
 69  Bwd Avg Bulk Rate             40000 non-null  int64
 70  Subflow Fwd Packets           40000 non-null  int64
 71   Subflow Fwd Bytes            40000 non-null  int64
 72   Subflow Bwd Packets          40000 non-null  int64
 73   Subflow Bwd Bytes            40000 non-null  int64
 74  Init_Win_bytes_forward        40000 non-null  int64
 75   Init_Win_bytes_backward      40000 non-null  int64
 76   act_data_pkt_fwd             40000 non-null  int64
 77   min_seg_size_forward         40000 non-null  int64
 78  Active Mean                   40000 non-null  float64
 79   Active Std                   40000 non-null  float64
 80   Active Max                   40000 non-null  int64
 81   Active Min                   40000 non-null  int64
 82  Idle Mean                     40000 non-null  float64
 83   Idle Std                     40000 non-null  float64
 84   Idle Max                     40000 non-null  int64
 85   Idle Min                     40000 non-null  int64
 86  SimillarHTTP                  40000 non-null  object
 87   Inbound                      40000 non-null  int64
 88   Label                        40000 non-null  object
dtypes: float64(26), int64(57), object(6)
memory usage: 27.2+ MB

In [8]:
# https://stackoverflow.com/questions/32075022/python-pandas-how-can-i-avoid-ellipsis-when-using-describe
# Set the maximum number of columns to display
pd.set_option('display.max_columns', None)

# Calculate summary statistics for the "dns" dataset
dns_summary = dns.describe()

# Display the summary statistics in a tidy table format
display(dns_summary)

# Reset the display option to its default value
pd.reset_option('display.max_columns')

,Unnamed: 0.1,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,40000.00000,40000.000000,40000.000000,40000.000000,40000.00000,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,40000.000000,40000.000000,3.999800e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.0,40000.0,40000.0,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,40000.000000,40000.000000,40000.000000,40000.000000,4.000000e+04,40000.0,40000.000000,40000.000000,40000.0,40000.00000,40000.000000,40000.000000,40000.0,40000.000000,40000.000000,40000.000000,40000.000000,4.000000e+04,40000.0,40000.0,40000.0,40000.0,40000.0,40000.0,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.00000,40000.000000,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,4.000000e+04,40000.000000
mean,19999.50000,6507.332600,4977.345450,31635.863850,16.53775,6.369008e+05,59.516775,0.401100,25446.258975,113.616125,1026.126000,996.106950,1019.851333,4.985696,16.85180,1.618050,4.999057,4.837025,inf,inf,3.535699e+04,7.420510e+04,3.006725e+05,8.167780e+03,6.073891e+05,4.509556e+04,8.437967e+04,2.850099e+05,8.113386e+03,4.157118e+05,3.012591e+04,6.512408e+04,1.914776e+05,0.094350,0.006125,0.0,0.0,0.0,-4.578263e+09,-5.312643e+04,9.504518e+05,5.889000e+02,996.006000,1035.926800,1021.274605,7.333277,2.595118e+03,0.0,0.000875,0.006125,0.0,0.01205,0.028250,0.017725,0.0,0.057175,1464.981247,1019.851333,4.999057,-4.578263e+09,0.0,0.0,0.0,0.0,0.0,0.0,59.516775,25446.258975,0.401100,113.616125,522.547275,193.62285,54.292925,-7.779886e+07,5.332603e+03,1.079421e+03,6.725740e+03,4.589863e+03,2.249085e+05,1.021299e+04,2.334430e+05,2.160931e+05,0.940575
std,11547.14972,6549.576074,15242.323757,19729.649291,2.23121,7.207313e+06,557.708939,4.639446,36714.184379,3432.397196,538.034635,572.719848,542.531526,31.411814,184.36744,13.892931,50.419597,57.523197,NaN,NaN,6.294230e+05,1.039170e+06,3.706117e+06,4.513965e+05,7.094838e+06,6.954929e+05,1.189174e+06,3.639536e+06,4.514064e+05,5.773357e+06,5.266894e+05,1.064472e+06,2.979074e+06,1.036038,0.078023,0.0,0.0,0.0,2.747697e+10,1.062719e+07,9.193014e+05,2.392320e+04,572.784031,545.110071,540.493799,50.412349,3.866857e+04,0.0,0.029568,0.078023,0.0,0.10911,0.165688,0.131952,0.0,0.331826,879.956771,542.531526,50.419597,2.747697e+10,0.0,0.0,0.0,0.0,0.0,0.0,557.708939,36714.184379,4.639446,3432.397196,4895.078762,2639.95185,85.221551,2.769050e+08,1.450657e+05,5.982480e+04,1.767886e+05,1.336954e+05,3.260212e+06,3.747078e+05,3.364290e+06,3.186050e+06,0.236421
min,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000e+00,3.929704e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,-2.530000e+11,-2.125438e+09,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-2.530000e+11,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.00000,0.000000,-1.408238e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,9999.75000,1575.000000,564.000000,14456.750000,17.00000,1.000000e+00,2.000000,0.000000,2944.000000,0.000000,440.000000,440.000000,440.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2.698372e+06,6.372877e+03,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,0.000000e+00,0.000000e+00,5.985649e+03,0.000000e+00,440.000000,440.000000,440.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,0.000000,442.200000,440.000000,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,2944.000000,0.000000,0.000000,-1.000000,-1.00000,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
50%,19999.50000,3273.000000,564.000000,31728.000000,17.00000,2.000000e+00,2.000000,0.000000,2944.000000,0.000000,1448.000000,1448.000000,1448.000000,0.000000,0.00000,0.000000,0.000000,0.000000,9.813333e+08,1.000000e+06,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,4.000000e+01,0.000000e+00,1.000000e+06,0.000000e+00,1448.000000,1448.000000,1448.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,0.000000,2172.000000,1448.000000,0.000000,4.000000e+01,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,2944.000000,0.000000,0.000000,-1.000000,-1.00000,1.000000,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,29999.25000,10417.000000,634.000000,48835.000000,17.00000,2.577950e+04,170.000000,0.000000,74800.000000,0.000000,1472.000000,1472.000000,1472.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2.944000e+09,2.000000e+06,1.631068e+02,1.896896e+02,9.300000e+02,2.000000e+00,2.458000e+04,1.471960e+02,1.684271e+02,7.132500e+02,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0,2.158000e+03,0.000000e+00,2.000000e+06,0.000000e+00,1472.000000,1472.000000,1472.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.0,0.00000,0.000000,0.000000,0.0,0.000000,2208.000000,1472.000000,0.000000,2.158000e+03,0.0,0.0,0.0,0.0,0.0,0.0,170.000000,74800.000000,0.000000,0.000000,-1.000000,-1.00000,169.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,39999.00000,27251.000000,65498.000000,65532.000000,17.00000,1.200000e+08,99068.000000,301.000000,176000.000000,446898.000000,3174.000000,2020.000000,2020.000000,1168.847509,3607.00000,378.000000,1806.285714,1398.644042,inf,inf,4.505603e+07,5.876782e+07,1.199384e+08,4.505603e+07,1.199999e+08,4.505603e+07,5.876782e+07,1.199384e+08,4.505603e+07,1.199999e+08,4.975526e+07,7.036456e+07,9.951052e+07,94.000000,1.000000,0.0,0.0,0.0,1.559380e+05,6.044000e+03,3.000000e+06,2.000000e+06,1472.000000,3607.000000,1510.344828,1270.079838,1.613103e+06,0.0,1.000000,1.000000,0.0,1.00000,1.000000,1.000000,0.0,13.000000,2208.000000,2020.000000,1806.285714,1.559380e+05,0.0,0.0,0.0,0.0,0.0,0.0,99068.000000,176000.000000,301.000000,446898.000000,65535.000000,64240.00000,399.000000,1.480000e+03,7.476217e+06,7.827056e+06,1.355686e+07,6.342870e+06,1.017888e+08,3.640597e+07,1.017888e+08,1.017888e+08,1.000000

In [9]:
# making a concatenated dataframe with whole datasets
df = pd.concat([dns, ldap, mssql, netbios, ntp, snmp, ssdp, syn, tftp, udp, udplag])

# Save the concatenated DataFrame to a CSV file
output_file_path = "C:\\Users\\user\\Documents\\jupyter\\Enhanced IDS\\Dataset\\concatenated_data.csv"
df.to_csv(output_file_path, index=False)  # index=False to not save the index column

In [10]:
df.shape

(440000, 89)

CONCLUSION:
1. All 10 dataset has been concatenate

NEXT ACTION:
1. Missing value found in Flow Bytes columns -- Requires Data Cleaning to remove row
2. 6 object columns founds -- Requires Data Transformation to convert to numerical form instead of categorical form